export const QUERY_KEYS = {
  ALERT: 'alert',
  ALERTS: 'alerts',
  ALERT_TYPE: 'alertType',
  ALERT_TYPES: 'alertTypes',
  COMMENT: 'comment',
  COMMENTS: 'comments',
  REPLIES: 'replies',
  HASHTAG: 'hashtag',
  HASHTAGS: 'hashtags',
  PLAYLIST_VIDEO: 'playlistVideo',
  PLAYLIST_VIDEOS: 'playlistVideos',
  USER: 'user',
  USERS: 'users',
  FOLLOW: 'follow',
  FOLLOWS: 'follows',
  FOLLOWINGS: 'followings',
  PLAYLIST: 'playlist',
  PLAYLISTS: 'playlists',
  SUBSCRIBE: 'subscribe',
  SUBSCRIBES: 'subscribes',
  LIKE: 'like',
  LIKES: 'likes',
  YOUTUBE_SEARCH: 'youtubeSearch',
  CATEGORIES: 'categories',
};
