name: Assign Issue Creator

on:
  issues:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign issue creator
        uses: actions-ecosystem/action-assign-issue@v1
        with:
          assignees: ${{ github.actor }}

      - name: Add label to issue
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: BugFix