name: Assign PR Creator and Reviewers

on:
  pull_request:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign PR creator
        uses: actions-ecosystem/action-assign-pull-request@v1
        with:
          assignees: ${{ github.actor }}
          reviewers: yulsanoh,duwlsssss,choiyoungae,vgotu99